"""upstream-pulse: the lockfile readers, and the judgements built on top of them.

Two things are being defended here. The first is that eight lockfile formats, written by eight
tools that agree on almost nothing, all come out the far side as the same four facts: name,
version, direct-or-transitive, production-or-dev. Every format gets a real file written to a real
temp tree, because a parser tested against a string someone wrote to make the test pass is not
tested at all.

The second is the architecture. This Play reports on public registries and does not open a socket:
the network half is a JSON partial another step writes, and this module reads it as data. If that
seam ever leaks — an `import urllib` added in a hurry — the whole claim these six Plays make about
the machine they run on goes with it, so it is asserted here as well as in the safety suite.
"""
import ast
import json
import pathlib
import tempfile
import unittest
from datetime import datetime, timezone
from pathlib import Path

from daily_core.common import Budget
from daily_core.parsers import lockfiles
from daily_core.scan import upstream

NOW = datetime(2026, 9, 5, 12, 0, tzinfo=timezone.utc)

MODULES = (pathlib.Path("daily_core/scan/upstream.py"),
           pathlib.Path("daily_core/parsers/lockfiles.py"))


# ---------------------------------------------------------------- a project of every shape

PACKAGE_LOCK_V3 = """{
  "name": "app",
  "lockfileVersion": 3,
  "packages": {
    "": {"name": "app",
         "dependencies": {"alpha": "^1.0.0"},
         "devDependencies": {"tester": "^2.0.0"}},
    "node_modules/alpha": {"version": "1.2.3", "dependencies": {"beta": "^3.0.0"}},
    "node_modules/beta": {"version": "3.1.0"},
    "node_modules/tester": {"version": "2.5.0", "dev": true,
                            "dependencies": {"gamma": "^1.0.0"}},
    "node_modules/gamma": {"version": "1.1.0", "dev": true}
  }
}
"""

PACKAGE_LOCK_V1 = """{
  "name": "legacy",
  "lockfileVersion": 1,
  "dependencies": {
    "one": {"version": "1.0.0", "requires": {"two": "^2.0.0"}},
    "two": {"version": "2.0.0"},
    "devtool": {"version": "1.5.0", "dev": true,
                "dependencies": {"nested-dev": {"version": "0.1.0", "dev": true}}}
  }
}
"""

PNPM_LOCK = """lockfileVersion: '9.0'

settings:
  autoInstallPeers: true

importers:

  .:
    dependencies:
      quick:
        specifier: ^1.0.0
        version: 1.4.0
    devDependencies:
      spec-runner:
        specifier: ^7.0.0
        version: 7.2.0

packages:

  quick@1.4.0:
    resolution: {integrity: sha512-aaa}

  slow@0.9.0:
    resolution: {integrity: sha512-bbb}

  spec-runner@7.2.0:
    resolution: {integrity: sha512-ccc}

snapshots:

  quick@1.4.0:
    dependencies:
      slow: 0.9.0

  slow@0.9.0: {}

  spec-runner@7.2.0: {}
"""

YARN_BERRY = """# This file is generated by running "yarn install"

__metadata:
  version: 6
  cacheKey: 8

"berry-app@workspace:.":
  version: 0.0.0-use.local
  resolution: "berry-app@workspace:."
  dependencies:
    ripe: "npm:^2.0.0"
  devDependencies:
    harness: "npm:^4.0.0"
  languageName: unknown
  linkType: soft

"harness@npm:4.1.0":
  version: 4.1.0
  resolution: "harness@npm:4.1.0"
  languageName: node
  linkType: hard

"ripe@npm:2.3.4":
  version: 2.3.4
  resolution: "ripe@npm:2.3.4"
  dependencies:
    tiny: "npm:^0.1.0"
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"tiny@npm:0.1.2":
  version: 0.1.2
  resolution: "tiny@npm:0.1.2"
  languageName: node
  linkType: hard
"""

YARN_CLASSIC = """# yarn lockfile v1


"@scope/tool@^3.0.0":
  version "3.3.3"
  resolved "https://registry.yarnpkg.com/@scope/tool/-/tool-3.3.3.tgz#ghi"
  integrity sha512-ghi

"classic-dep@^1.0.0":
  version "1.0.5"
  resolved "https://registry.yarnpkg.com/classic-dep/-/classic-dep-1.0.5.tgz#abc"
  integrity sha512-abc
  dependencies:
    sub-dep "^0.2.0"

sub-dep@^0.2.0:
  version "0.2.1"
  resolved "https://registry.yarnpkg.com/sub-dep/-/sub-dep-0.2.1.tgz#def"
  integrity sha512-def
"""

REQUIREMENTS = """# runtime
Requests==2.31.0
flask[async]>=2.0 ; python_version >= "3.9"
old-thing==0.4.2 \\
    --hash=sha256:deadbeef
-r requirements-dev.txt
"""

REQUIREMENTS_DEV = """pytest==8.0.0
Coverage==7.4.0
"""

PYPROJECT = """[tool.poetry]
name = "svc"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.27.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"
"""

POETRY_LOCK = """[[package]]
name = "httpx"
version = "0.27.0"
description = "an http client"
optional = false
python-versions = ">=3.8"
groups = ["main"]

[package.dependencies]
httpcore = "==1.*"

[[package]]
name = "httpcore"
version = "1.0.5"
description = "the core"
optional = false
python-versions = ">=3.8"
groups = ["main"]

[[package]]
name = "pytest"
version = "8.0.2"
description = "testing"
optional = false
python-versions = ">=3.8"
groups = ["dev"]

[metadata]
lock-version = "2.0"
"""

PIPFILE = """[[source]]
url = "https://pypi.org/simple"
name = "pypi"

[packages]
boto3 = "*"

[dev-packages]
mypy = "*"
"""

PIPFILE_LOCK = """{
  "_meta": {"pipfile-spec": 6},
  "default": {"boto3": {"version": "==1.34.0"}, "botocore": {"version": "==1.34.0"}},
  "develop": {"mypy": {"version": "==1.8.0"}}
}
"""

GO_MOD = """module example.com/svc

go 1.21

require (
\tgithub.com/spf13/cobra v1.8.0
\tgolang.org/x/text v0.14.0 // indirect
)

require github.com/rs/zerolog v1.32.0

replace example.com/old => ./local
"""

GO_SUM = """github.com/inconshreveable/mousetrap v1.1.0 h1:ggg=
github.com/inconshreveable/mousetrap v1.1.0/go.mod h1:hhh=
github.com/rs/zerolog v1.32.0 h1:eee=
github.com/rs/zerolog v1.32.0/go.mod h1:fff=
github.com/spf13/cobra v1.8.0 h1:aaa=
github.com/spf13/cobra v1.8.0/go.mod h1:bbb=
golang.org/x/text v0.14.0 h1:ccc=
golang.org/x/text v0.14.0/go.mod h1:ddd=
"""

CARGO_TOML = """[package]
name = "svc"
version = "0.1.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.19"

[dev-dependencies]
criterion = "0.5"
"""

CARGO_LOCK = """version = 3

[[package]]
name = "svc"
version = "0.1.0"
dependencies = [
 "criterion",
 "once_cell",
 "serde",
]

[[package]]
name = "criterion"
version = "0.5.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "ddd"

[[package]]
name = "once_cell"
version = "1.19.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "ccc"

[[package]]
name = "serde"
version = "1.0.197"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaa"
dependencies = [
 "serde_derive",
]

[[package]]
name = "serde_derive"
version = "1.0.197"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bbb"
"""

TREE = {
    "js-v3/package.json": '{"name":"app","dependencies":{"alpha":"^1.0.0"},'
                          '"devDependencies":{"tester":"^2.0.0"}}',
    "js-v3/package-lock.json": PACKAGE_LOCK_V3,
    "js-v1/package.json": '{"name":"legacy","dependencies":{"one":"^1.0.0"},'
                          '"devDependencies":{"devtool":"^1.0.0"}}',
    "js-v1/package-lock.json": PACKAGE_LOCK_V1,
    "js-pnpm/pnpm-lock.yaml": PNPM_LOCK,
    "js-berry/yarn.lock": YARN_BERRY,
    "js-classic/package.json": '{"name":"classic","dependencies":{"classic-dep":"^1.0.0"},'
                               '"devDependencies":{"@scope/tool":"^3.0.0"}}',
    "js-classic/yarn.lock": YARN_CLASSIC,
    "py-req/requirements.txt": REQUIREMENTS,
    "py-req/requirements-dev.txt": REQUIREMENTS_DEV,
    "py-poetry/pyproject.toml": PYPROJECT,
    "py-poetry/poetry.lock": POETRY_LOCK,
    "py-pipenv/Pipfile": PIPFILE,
    "py-pipenv/Pipfile.lock": PIPFILE_LOCK,
    "py-bare/Pipfile.lock": PIPFILE_LOCK,
    "go-svc/go.mod": GO_MOD,
    "go-svc/go.sum": GO_SUM,
    "rs-svc/Cargo.toml": CARGO_TOML,
    "rs-svc/Cargo.lock": CARGO_LOCK,
}


def _write_tree(root: Path):
    for rel, body in sorted(TREE.items()):
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(str(path), "w", encoding="utf-8") as fh:
            fh.write(body)
    return root


def _flat(card: str) -> str:
    """The card as one line of prose: box drawing gone, wrapped rows rejoined."""
    rows = [line.strip("\u2502\u250c\u2510\u2514\u2518\u251c\u2524\u2500 ")
            for line in card.splitlines()]
    return " ".join(" ".join(rows).split())


def _index(records):
    """{(lockfile, name): record} — every assertion below is about one row of one file."""
    return dict(((r["lockfile"], r["name"]), r) for r in records if r.get("kind") == "dep")


class LockfileTree(unittest.TestCase):
    """One temp tree, read once, then asserted format by format."""

    @classmethod
    def setUpClass(cls):
        cls._tmp = tempfile.TemporaryDirectory()
        cls.root = _write_tree(Path(cls._tmp.name))
        cls.sources, cls.records = upstream.read_source(
            "lockfiles", Budget(), {"root": str(cls.root)})
        cls.by = _index(cls.records)

    @classmethod
    def tearDownClass(cls):
        cls._tmp.cleanup()

    def kind(self, lockfile, name):
        row = self.by.get((lockfile, name))
        self.assertIsNotNone(row, "{0} is missing from {1}".format(name, lockfile))
        return (row["direct"], row["scope"])


# ---------------------------------------------------------------- format by format

class TestNpmLockfiles(LockfileTree):
    def test_package_lock_v3_reads_direct_and_dev_from_the_root_entry(self):
        f = "js-v3/package-lock.json"
        self.assertEqual(self.kind(f, "alpha"), (True, "production"))
        self.assertEqual(self.kind(f, "beta"), (False, "production"))
        self.assertEqual(self.kind(f, "tester"), (True, "development"))
        self.assertEqual(self.kind(f, "gamma"), (False, "development"))
        self.assertEqual(self.by[(f, "beta")]["path"], ["alpha", "beta"],
                         "a transitive package should carry the walk that reached it")
        self.assertEqual(self.by[(f, "alpha")]["version"], "1.2.3")

    def test_package_lock_v1_reads_the_nested_tree_and_its_dev_flags(self):
        f = "js-v1/package-lock.json"
        self.assertEqual(self.kind(f, "one"), (True, "production"))
        self.assertEqual(self.kind(f, "two"), (False, "production"))
        self.assertEqual(self.kind(f, "devtool"), (True, "development"))
        self.assertEqual(self.kind(f, "nested-dev"), (False, "development"),
                         "a package nested under a dev dependency is dev, not production")

    def test_pnpm_reads_importers_for_direct_and_snapshots_for_the_graph(self):
        f = "js-pnpm/pnpm-lock.yaml"
        self.assertEqual(self.kind(f, "quick"), (True, "production"))
        self.assertEqual(self.kind(f, "slow"), (False, "production"))
        self.assertEqual(self.kind(f, "spec-runner"), (True, "development"))
        self.assertEqual(self.by[(f, "quick")]["version"], "1.4.0")

    def test_yarn_berry_reads_the_workspace_entry_as_the_root(self):
        f = "js-berry/yarn.lock"
        self.assertEqual(self.kind(f, "ripe"), (True, "production"))
        self.assertEqual(self.kind(f, "tiny"), (False, "production"))
        self.assertEqual(self.kind(f, "harness"), (True, "development"))
        self.assertNotIn((f, "berry-app"), self.by, "the workspace itself is not a dependency")
        self.assertEqual(self.by[(f, "ripe")]["version"], "2.3.4")

    def test_yarn_classic_reads_descriptors_and_leans_on_the_manifest(self):
        f = "js-classic/yarn.lock"
        self.assertEqual(self.kind(f, "classic-dep"), (True, "production"))
        self.assertEqual(self.kind(f, "sub-dep"), (False, "production"))
        self.assertEqual(self.kind(f, "@scope/tool"), (True, "development"))
        self.assertEqual(self.by[(f, "classic-dep")]["version"], "1.0.5")


class TestPythonLockfiles(LockfileTree):
    def test_requirements_are_direct_and_the_file_name_decides_the_scope(self):
        self.assertEqual(self.kind("py-req/requirements.txt", "requests"), (True, "production"))
        self.assertEqual(self.by[("py-req/requirements.txt", "requests")]["version"], "2.31.0")
        self.assertEqual(self.kind("py-req/requirements.txt", "flask"), (True, "production"))
        self.assertEqual(self.kind("py-req/requirements.txt", "old-thing"), (True, "production"))
        self.assertEqual(self.by[("py-req/requirements.txt", "old-thing")]["version"], "0.4.2")
        self.assertEqual(self.kind("py-req/requirements-dev.txt", "pytest"), (True, "development"))
        self.assertEqual(self.kind("py-req/requirements-dev.txt", "coverage"), (True, "development"))

    def test_a_name_is_normalised_the_way_pypi_normalises_it(self):
        self.assertEqual(lockfiles.normalise("pypi", "Flask_SQL.Alchemy"), "flask-sql-alchemy")
        self.assertEqual(lockfiles.normalise("npm", "Left-Pad"), "Left-Pad")
        self.assertEqual(self.by[("py-req/requirements.txt", "requests")]["display"], "Requests")

    def test_poetry_reads_pyproject_for_direct_and_the_lock_for_the_graph(self):
        f = "py-poetry/poetry.lock"
        self.assertEqual(self.kind(f, "httpx"), (True, "production"))
        self.assertEqual(self.kind(f, "httpcore"), (False, "production"))
        self.assertEqual(self.kind(f, "pytest"), (True, "development"))
        self.assertEqual(self.by[(f, "httpcore")]["path"], ["httpx", "httpcore"])

    def test_pipfile_lock_uses_the_pipfile_next_to_it_when_there_is_one(self):
        f = "py-pipenv/Pipfile.lock"
        self.assertEqual(self.kind(f, "boto3"), (True, "production"))
        self.assertEqual(self.kind(f, "botocore"), (False, "production"))
        self.assertEqual(self.kind(f, "mypy"), (True, "development"))
        self.assertEqual(self.by[(f, "boto3")]["version"], "1.34.0")

    def test_a_lone_pipfile_lock_says_it_cannot_tell_rather_than_guessing(self):
        f = "py-bare/Pipfile.lock"
        self.assertIsNone(self.by[(f, "boto3")]["direct"],
                          "with no Pipfile there is no way to know, and None is the honest answer")
        self.assertIsNone(self.by[(f, "botocore")]["direct"])
        self.assertEqual(self.by[(f, "mypy")]["scope"], "development")
        self.assertIn("cannot be told apart", self.by[(f, "boto3")]["direct_basis"])


class TestGoAndCargoLockfiles(LockfileTree):
    def test_go_reads_indirect_markers_and_folds_go_sum_into_go_mod(self):
        f = "go-svc/go.sum"
        self.assertEqual(self.kind(f, "github.com/spf13/cobra"), (True, "production"))
        self.assertEqual(self.kind(f, "github.com/rs/zerolog"), (True, "production"),
                         "a require line outside a block counts too")
        self.assertEqual(self.kind(f, "golang.org/x/text"), (False, "production"),
                         "// indirect is exactly what transitive means in go.mod")
        self.assertEqual(self.kind(f, "github.com/inconshreveable/mousetrap"),
                         (False, "production"), "in go.sum only, so it was nobody's direct choice")
        self.assertEqual(self.by[(f, "github.com/spf13/cobra")]["version"], "v1.8.0")
        self.assertNotIn(("go-svc/go.mod", "github.com/spf13/cobra"), self.by,
                         "go.mod beside a go.sum is the manifest, not a second lockfile")

    def test_cargo_reads_the_manifest_for_direct_and_the_lock_for_the_graph(self):
        f = "rs-svc/Cargo.lock"
        self.assertEqual(self.kind(f, "serde"), (True, "production"))
        self.assertEqual(self.kind(f, "serde_derive"), (False, "production"))
        self.assertEqual(self.kind(f, "once_cell"), (True, "production"))
        self.assertEqual(self.kind(f, "criterion"), (True, "development"))
        self.assertNotIn((f, "svc"), self.by, "your own crate is the root, not a dependency")
        self.assertEqual(self.by[(f, "serde")]["version"], "1.0.197")

    def test_every_lockfile_in_the_tree_was_found_and_read(self):
        found = sorted(set(r["lockfile"] for r in self.records))
        self.assertEqual(found, ["go-svc/go.sum", "js-berry/yarn.lock", "js-classic/yarn.lock",
                                 "js-pnpm/pnpm-lock.yaml", "js-v1/package-lock.json",
                                 "js-v3/package-lock.json", "py-bare/Pipfile.lock",
                                 "py-pipenv/Pipfile.lock", "py-poetry/poetry.lock",
                                 "py-req/requirements-dev.txt", "py-req/requirements.txt",
                                 "rs-svc/Cargo.lock"])

    def test_every_row_names_how_direct_ness_was_decided(self):
        for r in self.records:
            self.assertTrue(r["direct_basis"], "{0} has no stated basis".format(r["lockfile"]))


class TestHandWrittenReaders(unittest.TestCase):
    def test_the_yaml_reader_handles_the_shapes_lockfiles_use(self):
        doc = lockfiles.mini_yaml(
            "top: 1\n"
            "# a comment\n"
            "quoted: \"a: b\"\n"
            'flags: {a: 1, b: 2}\n'
            "nest:\n"
            "  inner: yes please\n"
            "  deeper:\n"
            "    leaf: true\n"
            "items:\n"
            "  - one\n"
            "  - two\n")
        self.assertEqual(doc["top"], "1")
        self.assertEqual(doc["quoted"], "a: b")
        self.assertEqual(doc["flags"], "{a: 1, b: 2}", "flow collections stay opaque on purpose")
        self.assertEqual(doc["nest"]["inner"], "yes please")
        self.assertTrue(doc["nest"]["deeper"]["leaf"])
        self.assertEqual(doc["items"], ["one", "two"])

    def test_the_toml_reader_handles_arrays_of_tables_and_inline_tables(self):
        doc = lockfiles.mini_toml(
            'version = 3\n'
            '# comment\n'
            'name = "with # hash"\n'
            '[[package]]\n'
            'name = "a"\n'
            'deps = [\n  "x",\n  "y",\n]\n'
            '[package.meta]\n'
            'kind = "lib"\n'
            '[[package]]\n'
            'name = "b"\n'
            '[table]\n'
            'inline = { version = "1.0", features = ["derive"] }\n')
        self.assertEqual(doc["version"], 3)
        self.assertEqual(doc["name"], "with # hash", "a hash inside a string is not a comment")
        self.assertEqual([p["name"] for p in doc["package"]], ["a", "b"])
        self.assertEqual(doc["package"][0]["deps"], ["x", "y"])
        self.assertEqual(doc["package"][0]["meta"]["kind"], "lib",
                         "a sub-table attaches to the last entry of the array above it")
        self.assertEqual(doc["table"]["inline"]["features"], ["derive"])

    def test_an_unreadable_lockfile_is_a_note_not_an_exception(self):
        result = lockfiles.parse("package-lock.json", "{not json at all")
        self.assertFalse(result["ok"])
        self.assertTrue(result["note"])
        self.assertEqual(lockfiles.resolve(result), [])

    def test_a_file_this_play_does_not_read_says_so(self):
        self.assertFalse(lockfiles.parse("composer.lock", "{}")["ok"])
        self.assertFalse(lockfiles.is_lockfile("composer.lock"))
        self.assertTrue(lockfiles.is_lockfile("requirements-test.txt"))


# ---------------------------------------------------------------- the registry half

def _dep(name, ecosystem="npm", version="1.0.0", direct=True, scope="production", depth=0,
         path=None, lockfile="package-lock.json", local=False):
    return {"kind": "dep", "name": name, "display": name, "ecosystem": ecosystem,
            "version": version, "direct": direct, "scope": scope, "depth": depth,
            "path": path or [name], "local": local, "lockfile": lockfile,
            "format": "package-lock.json (lockfileVersion 3)",
            "direct_basis": "the package.json next to it"}


def _reg(name, ecosystem="npm", **kw):
    entry = {"kind": "registry", "name": name, "ecosystem": ecosystem,
             "pinned_version": "1.0.0", "latest_version": "1.0.0",
             "last_release_date": "2026-08-01T00:00:00Z",
             "release_dates": ["2026-02-01T00:00:00Z", "2026-08-01T00:00:00Z",
                               "2025-06-01T00:00:00Z"],
             "maintainer_count": 5, "deprecated": False, "deprecation_message": "",
             "repository_archived": False, "license": "MIT", "pinned_license": "MIT",
             "successor": "", "error": ""}
    entry.update(kw)
    return entry


def _meta(cached_at="2026-09-05T09:00:00Z", **kw):
    doc = {"kind": "registry_meta", "cached_at": cached_at, "source": "registry.npmjs.org",
           "requested": 0, "returned": 0}
    doc.update(kw)
    return doc


ABANDONED = dict(last_release_date="2019-01-04T00:00:00Z",
                 release_dates=["2016-03-23T00:00:00Z", "2019-01-04T00:00:00Z"],
                 maintainer_count=1, latest_version="1.3.0", pinned_version="1.0.0")


class TestDormancyGrade(unittest.TestCase):
    def test_every_input_to_the_grade_is_printed_with_its_own_points(self):
        graded = upstream.score(_reg("left-pad", **ABANDONED), NOW, {})
        names = [s["signal"] for s in graded["signals"]]
        self.assertEqual(names, list(upstream.SIGNAL_ORDER),
                         "every input must appear, in a fixed order, every time")
        self.assertEqual(sum(s["points"] for s in graded["signals"]), graded["points"],
                         "the printed inputs must add up to the printed score")
        self.assertEqual(sum(s["max"] for s in graded["signals"]), graded["max_points"])
        for s in graded["signals"]:
            self.assertTrue(s["value"], "{0} printed no reading".format(s["signal"]))
            self.assertTrue(s["why"], "{0} printed no scoring rule".format(s["signal"]))
            self.assertLessEqual(s["points"], s["max"])
        self.assertIn(graded["grade"], ("D", "F"))
        self.assertTrue(graded["dormant"])
        self.assertTrue(graded["single_maintainer"])

    def test_a_healthy_package_grades_a_and_still_prints_all_seven_inputs(self):
        graded = upstream.score(_reg("well-kept"), NOW, {})
        self.assertEqual(graded["grade"], "A")
        self.assertEqual(len(graded["signals"]), len(upstream.SIGNAL_ORDER))
        self.assertFalse(graded["dormant"])
        self.assertFalse(graded["single_maintainer"])

    def test_an_unknown_input_scores_zero_and_is_labelled_unknown_rather_than_good(self):
        graded = upstream.score(_reg("mystery", maintainer_count=None, last_release_date="",
                                     release_dates=[], pinned_license=""), NOW, {})
        unknown = graded["unknown_inputs"]
        self.assertIn("publishers", unknown)
        self.assertIn("last release", unknown)
        self.assertIn("release cadence", unknown)
        self.assertIn("licence", unknown)
        self.assertIsNone(graded["dormant"], "not knowing is not the same as not dormant")
        self.assertIsNone(graded["single_maintainer"])
        for s in graded["signals"]:
            if s["unknown"]:
                self.assertEqual(s["points"], 0)

    def test_deprecation_archival_and_a_licence_change_are_each_their_own_input(self):
        graded = upstream.score(_reg("gone", deprecated=True, repository_archived=True,
                                     pinned_license="MIT", license="BUSL-1.1"), NOW, {})
        points = dict((s["signal"], s["points"]) for s in graded["signals"])
        self.assertEqual(points["deprecation"], 3)
        self.assertEqual(points["repository"], 2)
        self.assertEqual(points["licence"], 1)
        self.assertTrue(graded["licence_changed"])

    def test_cadence_reads_the_release_dates_rather_than_only_the_newest(self):
        slowing = upstream.score(_reg("slowing", release_dates=[
            "2025-01-01T00:00:00Z", "2025-04-01T00:00:00Z", "2025-08-01T00:00:00Z",
            "2026-03-01T00:00:00Z"]), NOW, {})
        cadence = [s for s in slowing["signals"] if s["signal"] == "release cadence"][0]
        self.assertEqual(cadence["points"], 1, "three releases then one is slowing")
        self.assertIn("this year", cadence["value"])


class TestBlastRadiusAndTheHeadlineClass(unittest.TestCase):
    def build(self, cfg=None):
        records = [
            _dep("left-pad"), _dep("dev-only", scope="development"),
            _dep("deep", direct=False, depth=2, path=["left-pad", "mid", "deep"]),
            _reg("left-pad", **ABANDONED),
            _reg("dev-only", **ABANDONED),
            _reg("deep", **ABANDONED),
            _meta(),
        ]
        return upstream.analyse(records, NOW, cfg or {"depth": 2})

    def test_a_dormant_package_is_placed_in_production_or_in_dev_and_test(self):
        v = self.build()
        by = dict((p["display"], p) for p in v["packages"])
        self.assertEqual(by["left-pad"]["blast"]["radius"], "production")
        self.assertEqual(by["dev-only"]["blast"]["radius"], "dev/test")
        self.assertEqual(by["deep"]["blast"]["radius"], "production")
        self.assertIn("left-pad → mid → deep", by["deep"]["blast"]["why"],
                      "the walk that reached it is the evidence, and it should be printed")

    def test_the_headline_class_is_named_and_counted_separately_from_the_rest(self):
        v = self.build()
        self.assertEqual(v["headline"]["class"], upstream.HEADLINE_CLASS)
        self.assertIn("single-publisher", v["headline"]["class"])
        self.assertIn("dormant", v["headline"]["class"])
        self.assertIn("production", v["headline"]["class"])
        names = sorted(p["name"] for p in v["headline"]["packages"])
        self.assertEqual(names, ["deep", "left-pad"])
        self.assertEqual(v["headline"]["both"], 3)
        self.assertEqual(v["headline"]["count"], 2)
        self.assertEqual([p["name"] for p in v["headline"]["also_dev"]], ["dev-only"])

    def test_transitive_lookups_are_off_by_default_and_say_so(self):
        v = upstream.analyse([
            _dep("left-pad"), _dep("deep", direct=False, depth=2),
            _reg("left-pad", **ABANDONED), _reg("deep", **ABANDONED), _meta()], NOW, {})
        by = dict((p["display"], p) for p in v["packages"])
        self.assertEqual(by["deep"]["check_state"], "not requested")
        self.assertEqual(by["deep"]["grade"], upstream.UNKNOWN_GRADE)
        self.assertEqual(by["left-pad"]["check_state"], "checked")
        self.assertFalse(v["depth"]["transitive_included"])
        self.assertIn("rate limit", v["depth"]["note"])
        v2 = upstream.analyse([
            _dep("left-pad"), _dep("deep", direct=False, depth=2),
            _reg("left-pad", **ABANDONED), _reg("deep", **ABANDONED), _meta()], NOW, {"depth": 3})
        self.assertEqual(dict((p["display"], p) for p in v2["packages"])["deep"]["check_state"],
                         "checked")

    def test_a_lockfile_that_cannot_place_a_package_does_not_call_it_dev_only(self):
        v = upstream.analyse([_dep("floating", scope="unknown", direct=None),
                              _reg("floating", **ABANDONED), _meta()], NOW, {})
        pkg = v["packages"][0]
        self.assertEqual(pkg["blast"]["radius"], "unknown")
        self.assertEqual(v["totals"]["scope_unknown"], 1)
        self.assertEqual(v["totals"]["development"], 0)
        self.assertEqual(v["totals"]["direct_unknown"], 1)
        self.assertIn("not counted as dev/test", pkg["blast"]["why"])


class TestReplacementHints(unittest.TestCase):
    def test_a_successor_is_reported_only_when_the_registry_names_one(self):
        v = upstream.analyse([
            _dep("named"), _dep("unnamed"),
            _reg("named", deprecated=True, successor="modern-thing",
                 deprecation_message="this package moved"),
            _reg("unnamed", deprecated=True, successor="",
                 deprecation_message="please use modern-thing instead"),
            _meta()], NOW, {})
        hints = dict((r["name"], r) for r in v["replacements"])
        self.assertEqual(sorted(hints), ["named"])
        self.assertEqual(hints["named"]["successor"], "modern-thing")
        self.assertIn("successor field", hints["named"]["source"])

    def test_a_name_inside_a_deprecation_message_is_never_mined_for_a_hint(self):
        hint = upstream.replacement(_reg(
            "unnamed", deprecated=True, successor="",
            deprecation_message="this is dead, switch to shiny-replacement"))
        self.assertEqual(hint["successor"], "", "prose is not a machine-readable successor field")
        self.assertEqual(hint["source"], "")
        self.assertIn("shiny-replacement", hint["message"],
                      "the publisher's own words are still quoted, verbatim, as words")

    def test_deprecated_packages_with_no_successor_are_counted_rather_than_given_one(self):
        v = upstream.analyse([_dep("unnamed"), _reg("unnamed", deprecated=True), _meta()], NOW, {})
        self.assertEqual(v["replacements"], [])
        self.assertEqual([p["name"] for p in v["deprecated_without_successor"]], ["unnamed"])
        report = upstream.report_markdown(v, {}, [])
        self.assertIn("does not guess one for them", report)


class TestOfflineMode(unittest.TestCase):
    def deps(self):
        return [_dep("alpha"), _dep("beta"), _dep("gamma", direct=False, depth=1)]

    def test_a_missing_partial_still_reports_the_whole_inventory(self):
        v = upstream.analyse(self.deps(), NOW, {})
        self.assertTrue(v["network"]["offline"])
        self.assertEqual(v["totals"]["packages"], 3)
        self.assertEqual(v["totals"]["direct"], 2)
        self.assertEqual(v["totals"]["transitive"], 1)
        self.assertEqual(v["checks"]["checked"], 0)
        self.assertIn("did not run", v["network"]["reason"])

    def test_nothing_unchecked_is_ever_graded_or_called_healthy(self):
        v = upstream.analyse(self.deps(), NOW, {})
        for p in v["packages"]:
            self.assertEqual(p["grade"], upstream.UNKNOWN_GRADE)
            self.assertIsNone(p["points"])
            self.assertIsNone(p["dormant"], "unchecked is not the same as not dormant")
            self.assertIsNone(p["single_maintainer"])
            self.assertFalse(p["deprecated"])
        self.assertEqual(v["grades"]["A"], 0, "an unchecked package must never land in grade A")
        self.assertEqual(v["grades"][upstream.UNKNOWN_GRADE], 3)
        self.assertIn("Nothing here says these packages are healthy", " ".join(v["notes"]))

    def test_a_partial_where_every_lookup_failed_is_offline_too(self):
        v = upstream.analyse(self.deps() + [
            _reg("alpha", error="ETIMEDOUT"), _reg("beta", error="ETIMEDOUT"), _meta()], NOW, {})
        self.assertTrue(v["network"]["offline"])
        self.assertEqual(v["checks"]["failed"], 2)
        self.assertIn("reported an error", v["network"]["reason"])
        self.assertEqual(v["grades"][upstream.UNKNOWN_GRADE], 3)

    def test_the_card_and_the_report_both_say_the_network_half_is_unknown(self):
        v = upstream.analyse(self.deps(), NOW, {})
        card = _flat(upstream.render(v, {}))
        self.assertIn("No registry answer", card)
        self.assertIn("only that nobody asked", card)
        report = upstream.report_markdown(v, {}, [])
        self.assertIn("The network half did not answer", report)
        self.assertIn("which is complete", report)

    def test_a_missing_partial_on_disk_is_a_labelled_source_not_a_crash(self):
        with tempfile.TemporaryDirectory() as tmp:
            sources, records = upstream.read_source("registry", Budget(), {"out_dir": tmp})
            self.assertEqual(records, [])
            self.assertFalse(sources[0].found)
            self.assertIn("did not run", sources[0].note)

    def test_a_partial_from_a_future_schema_is_ignored_with_a_reason(self):
        with tempfile.TemporaryDirectory() as tmp:
            with open(str(Path(tmp) / upstream.PARTIAL), "w", encoding="utf-8") as fh:
                fh.write(json.dumps({"schema": 99, "packages": [{"name": "x"}]}))
            sources, records = upstream.read_source("registry", Budget(), {"out_dir": tmp})
            self.assertEqual(records, [])
            self.assertIn("schema 99", sources[0].note)


class TestCacheAwareness(unittest.TestCase):
    def test_a_re_run_inside_the_window_says_it_is_answering_from_yesterday(self):
        v = upstream.analyse([_dep("alpha"), _reg("alpha"),
                              _meta(cached_at="2026-09-04T20:00:00Z")], NOW, {})
        self.assertEqual(v["cache"]["age_hours"], 16.0)
        self.assertTrue(v["cache"]["within_window"])
        self.assertEqual(v["cache"]["window_hours"], upstream.CACHE_HOURS)
        self.assertIn("yesterday's facts", v["cache"]["note"])

    def test_a_narrower_window_makes_the_same_data_stale(self):
        v = upstream.analyse([_dep("alpha"), _reg("alpha"),
                              _meta(cached_at="2026-09-04T20:00:00Z")], NOW, {"cache_hours": 4})
        self.assertFalse(v["cache"]["within_window"])
        self.assertIn("past the 4h cache window", v["cache"]["note"])

    def test_a_partial_with_no_timestamp_says_the_age_is_unknown(self):
        v = upstream.analyse([_dep("alpha"), _reg("alpha"), _meta(cached_at="")], NOW, {})
        self.assertIsNone(v["cache"]["age_hours"])
        self.assertIn("unknown", v["cache"]["note"])

    def test_the_cache_note_reaches_the_card(self):
        v = upstream.analyse([_dep("alpha"), _reg("alpha"),
                              _meta(cached_at="2026-09-04T20:00:00Z")], NOW, {})
        self.assertIn("16.0h old", _flat(upstream.render(v, {})))


class TestUnknownEcosystems(unittest.TestCase):
    def test_a_package_from_an_ecosystem_this_play_cannot_query_is_kept_and_labelled(self):
        v = upstream.analyse([_dep("alpha"), _dep("monolog/monolog", ecosystem="packagist",
                                                  lockfile="composer.lock"),
                              _reg("alpha"), _meta()], NOW, {})
        by = dict((p["display"], p) for p in v["packages"])
        self.assertIn("monolog/monolog", by, "an unpriced package is never silently dropped")
        self.assertEqual(by["monolog/monolog"]["check_state"], "unpriced")
        self.assertEqual(by["monolog/monolog"]["grade"], upstream.UNKNOWN_GRADE)
        self.assertFalse(by["monolog/monolog"]["checkable"])
        self.assertEqual(v["unpriced"]["count"], 1)
        self.assertEqual(v["unpriced"]["ecosystems"], ["packagist"])
        self.assertEqual(v["totals"]["packages"], 2)
        self.assertIn("packagist", upstream.report_markdown(v, {}, []))

    def test_an_entry_whose_ecosystem_does_not_match_never_grades_the_wrong_package(self):
        v = upstream.analyse([_dep("shared"), _reg("shared", ecosystem="pypi"), _meta()], NOW, {})
        self.assertEqual(v["packages"][0]["check_state"], "missing",
                         "an npm package is not answered by a pypi lookup of the same name")


class TestViewAndPresentation(unittest.TestCase):
    def view(self):
        records = [
            _dep("left-pad"), _dep("dev-only", scope="development"),
            _dep("well-kept"), _dep("deep", direct=False, depth=1, path=["left-pad", "deep"]),
            _dep("monolog/monolog", ecosystem="packagist", lockfile="composer.lock"),
            _reg("left-pad", deprecated=True, successor="String.prototype.padStart", **ABANDONED),
            _reg("dev-only", **ABANDONED),
            _reg("well-kept"),
            _meta(cached_at="2026-09-05T06:00:00Z"),
        ]
        return upstream.analyse(records, NOW, {})

    def test_the_card_is_sixty_four_columns_and_carries_the_headline_shape(self):
        card = upstream.render(self.view(), {})
        widths = set(len(line) for line in card.splitlines())
        self.assertEqual(widths, {64}, "every row of the card is the same width")
        flat = _flat(card)
        self.assertIn("direct dependencies", flat)
        self.assertIn("no release in 2.0 years", flat)
        self.assertIn("single-publisher", flat)
        self.assertIn("production request path", flat)
        self.assertNotIn("\u2026", flat.split("DORMANCY")[0],
                         "the headline must never be truncated away")

    def test_the_card_shows_the_grade_spread_as_a_tier_bar_with_a_legend(self):
        v = self.view()
        card = upstream.render(v, {})
        self.assertEqual([g for g, _ in v["grade_tiers"]], ["F", "D", "C", "B", "A"])
        self.assertTrue(any("█" in line for line in card.splitlines()))
        self.assertIn("█ F", card)

    def test_the_card_prints_every_input_to_the_worst_grade(self):
        card = _flat(upstream.render(self.view(), {}))
        for signal in upstream.SIGNAL_ORDER:
            self.assertIn(signal, card, "{0} never reached the card".format(signal))
        self.assertIn("blast radius", card)

    def test_the_report_gives_every_number_a_denominator(self):
        v = self.view()
        report = upstream.report_markdown(v, {}, [])
        self.assertIn("| direct dependencies | {0} | {1} packages |".format(
            v["totals"]["direct"], v["totals"]["packages"]), report)
        self.assertIn("| dev/test only | {0} | {1} packages |".format(
            v["totals"]["development"], v["totals"]["packages"]), report)
        self.assertIn("of {0} checked packages are both dormant".format(v["checks"]["checked"]),
                      report)
        self.assertIn("A 0-1 · B 2-3 · C 4-6 · D 7-9 · F 10+", report)

    def test_the_view_carries_the_keys_the_cli_joins_on(self):
        v = self.view()
        for key in ("totals", "checks", "network", "cache", "depth", "grades", "grade_tiers",
                    "dormant", "single_maintainer", "headline", "worst", "replacements",
                    "packages", "unpriced", "lockfiles", "ecosystems", "snapshot", "delta",
                    "since", "notes"):
            self.assertIn(key, v)
        json.dumps(v)                          # the whole view has to survive the step contract

    def test_a_baseline_round_trips_and_the_delta_reports_movement(self):
        with tempfile.TemporaryDirectory() as tmp:
            first = upstream.analyse([_dep("left-pad"), _reg("left-pad", **ABANDONED), _meta()],
                                     NOW, {"out_dir": tmp})
            self.assertTrue(first["delta"]["first_run"])
            upstream.save_baseline(first, {"out_dir": tmp}, NOW)
            second = upstream.analyse([_dep("left-pad"), _dep("newcomer"),
                                       _reg("left-pad", **ABANDONED), _reg("newcomer"), _meta()],
                                      NOW, {"out_dir": tmp})
            self.assertFalse(second["delta"]["first_run"])
            self.assertIn("npm:newcomer", second["delta"]["added"])
            self.assertIn("@packages", second["delta"]["grew"])


class TestDeterminism(unittest.TestCase):
    def test_the_same_records_and_the_same_clock_give_the_same_answer(self):
        records = [_dep("b"), _dep("a"), _dep("c", scope="development"),
                   _reg("a", **ABANDONED), _reg("b"), _reg("c"), _meta()]
        first = upstream.analyse(list(records), NOW, {})
        second = upstream.analyse(list(reversed(records)), NOW, {})
        self.assertEqual(json.dumps(first, sort_keys=True, default=str),
                         json.dumps(second, sort_keys=True, default=str))
        self.assertEqual(upstream.render(first, {}), upstream.render(second, {}))
        self.assertEqual(upstream.report_markdown(first, {}, []),
                         upstream.report_markdown(second, {}, []))

    def test_reading_the_same_tree_twice_gives_the_same_records(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = _write_tree(Path(tmp))
            _s1, first = upstream.read_source("lockfiles", Budget(), {"root": str(root)})
            _s2, second = upstream.read_source("lockfiles", Budget(), {"root": str(root)})
            self.assertEqual(json.dumps(first, sort_keys=True), json.dumps(second, sort_keys=True))


class TestDemoMode(unittest.TestCase):
    def test_demo_mode_reads_bundled_lockfiles_and_a_bundled_partial(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = _write_tree(Path(tmp))
            with open(str(root / upstream.DEMO_REGISTRY), "w", encoding="utf-8") as fh:
                fh.write(json.dumps({
                    "schema": 1, "cached_at": "2026-09-05T06:00:00Z", "source": "demo",
                    "packages": [{"name": "alpha", "ecosystem": "npm", "pinned_version": "1.2.3",
                                  "latest_version": "1.3.0",
                                  "last_release_date": "2019-01-04T00:00:00Z",
                                  "release_dates": ["2019-01-04T00:00:00Z"],
                                  "maintainer_count": 1, "deprecated": False,
                                  "repository_archived": True, "license": "MIT",
                                  "pinned_license": "MIT", "successor": ""}]}))
            cfg = {"demo_root": str(root)}
            lock_sources, deps = upstream.read_source("lockfiles", Budget(), cfg)
            reg_sources, reg = upstream.read_source("registry", Budget(), cfg)
            self.assertTrue(lock_sources[0].found)
            self.assertIn("(demo)", lock_sources[0].name)
            self.assertTrue(reg_sources[0].found)
            v = upstream.analyse(deps + reg, NOW, cfg)
            alpha = [p for p in v["packages"] if p["display"] == "alpha"][0]
            self.assertEqual(alpha["check_state"], "checked")
            self.assertIn(alpha["grade"], ("D", "F"))
            self.assertFalse(v["network"]["offline"])
            self.assertEqual(len(upstream.render(v, cfg).splitlines()[0]), 64)

    def test_a_root_with_no_lockfile_is_a_labelled_miss(self):
        with tempfile.TemporaryDirectory() as tmp:
            sources, records = upstream.read_source("lockfiles", Budget(), {"root": tmp})
            self.assertEqual(records, [])
            self.assertFalse(sources[0].found)
            self.assertIn("no lockfile", sources[0].note)

    def test_an_unknown_source_name_is_a_miss_rather_than_an_exception(self):
        sources, records = upstream.read_source("nonsense", Budget(), {})
        self.assertEqual(records, [])
        self.assertFalse(sources[0].found)


# ---------------------------------------------------------------- the architecture itself

class TestTheNetworkSeam(unittest.TestCase):
    """The reason the registry answers arrive as a file instead of as a response."""

    BANNED = ("urllib", "http", "https", "socket", "ssl", "requests", "ftplib", "smtplib",
              "asyncio", "selectors", "telnetlib", "xmlrpc", "aiohttp", "httpx")

    def test_neither_module_imports_anything_that_can_reach_a_network(self):
        for path in MODULES:
            tree = ast.parse(path.read_text(encoding="utf-8"))
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        self.assertNotIn(alias.name.split(".")[0], self.BANNED,
                                         "{0} imports {1}".format(path, alias.name))
                elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
                    self.assertNotIn(node.module.split(".")[0], self.BANNED,
                                     "{0} imports from {1}".format(path, node.module))

    def test_neither_module_names_a_way_to_open_a_connection(self):
        for path in MODULES:
            text = path.read_text(encoding="utf-8")
            for banned in ("urlopen", "urlretrieve", "create_connection", "HTTPSConnection",
                           "import subproc" + "ess", "os.system", "popen"):
                self.assertNotIn(banned, text, "{0} references {1}".format(path, banned))

    def test_both_modules_are_stdlib_only_and_parse_as_python_39(self):
        allowed = {"json", "re", "ast", "os", "collections", "dataclasses", "datetime", "pathlib"}
        for path in MODULES:
            source = path.read_text(encoding="utf-8")
            ast.parse(source, feature_version=(3, 9))
            for node in ast.walk(ast.parse(source)):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        self.assertIn(alias.name.split(".")[0], allowed, str(path))

    def test_the_partial_schema_is_documented_where_the_next_sprint_will_look_for_it(self):
        doc = upstream.__doc__ or ""
        for field in ("name", "ecosystem", "pinned_version", "latest_version", "last_release_date",
                      "release_dates", "maintainer_count", "deprecated", "deprecation_message",
                      "repository_archived", "license", "successor", "cached_at", "schema"):
            self.assertIn(field, doc, "{0} is not documented in the partial's schema".format(field))
        self.assertIn(upstream.PARTIAL, doc)


if __name__ == "__main__":
    unittest.main()
